spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DATA_SOURCE_DRIVER}
    initialization-mode: ${DB_INIT_MODE}
    hikari:
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT}
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE}
      max-lifetime: ${HIKARI_MAX_LIFETIME}
      minimum-idle: ${HIKARI_MINIMUM_IDLE}
  jpa:
    properties:
      hibernate:
        dialect: ${DB_JPA_DIALECT}
    hibernate:
      ddl-auto: ${DB_JPA_DDL_AUTO}

info:
  application:
    name: Posterr API
    description: Provide operations for Posterr applications envolving Posts domain
    author:
      name: Renan Silva
      bio: Avid and curious learner