spring:
  #  datasource:
  #    url: ${DB_URL}
  #    username: ${DB_USER}
  #    password: ${DB_PASSWORD}
  #    driver-class-name: ${DB_DATA_SOURCE_DRIVER}
  #  jpa:
  #    properties:
  #      hibernate:
  #        dialect: ${DB_JPA_DIALECT}
  #    hibernate:
  #      ddl-auto: ${DB_JPA_DDL_AUTO}
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: rg.hibernate.dialect.H2Dialect
info:
  application:
    name: Posterr API
    description: Provide operations for Posterr applications envolving Posts domain
    author:
      name: Renan Silva
      bio: Avid and curious learner