swagger: '2.0'

info:
  title: Posterr Rest API
  description: Provide operations for Posterr applications envolving Posts domain
  version: 1.0.0
  contact:
    name: 'Renan Pedro da Silva'
    email: 'rpedrodasilva10@gmail.com'

host: springboot-clients-api.herokuapp.com

basePath: /api/v1
schemes:
  - https
tags:
  - name: Public
    description: Public operations

parameters:
  onlyMyPosts:
    in: query
    name: onlyMyPosts
    required: true
    type: integer
    enum: [0, 1]
    description: 'Inform if the service must return only the user posts or '
  post:
    in: body
    name: post
    required: true
    schema:
      $ref: '#/definitions/CreatePostRequest'
    description: 'Payload to create a post'
  skip:
    in: query
    name: skip
    required: false
    type: integer
    description: 'Rows to skip from the result'
  limit:
    in: query
    name: limit
    required: false
    type: integer
    default: 20
    description: 'Rows to limit the result (the default value is 20)'
  startDate:
    in: query
    name: startDate
    required: false
    type: string
    format: date
    description: 'Start date to filter posts'
  endDate:
    in: query
    name: endDate
    required: false
    type: string
    format: date
    description: 'End date to filter posts'


responses:
  200-Ok:
    description: 'Successful Request'
    schema:
      $ref: '#/definitions/Post'
  200-OkList:
    description: 'Successful Request'
    schema:
      $ref: '#/definitions/ClientList'
  201-Created:
    description: 'Created'
    schema:
      $ref: '#/definitions/CreatedPost'
  204-NoContent:
    description: 'No content'
  400-BadRequest:
    description: 'Bad request'
    schema:
      $ref: '#/definitions/ApiError'
  401-Unauthorized:
    description: 'Unauthorized'
    schema:
      $ref: '#/definitions/ApiError'
  403-Forbidden:
    description: 'Forbidden'
    schema:
      $ref: '#/definitions/ApiError'
  404-NotFound:
    description: 'Not found'
    schema:
      $ref: '#/definitions/ApiError'
  405-DataInvalid:
    description: 'Data input not supplied or invalid'
    schema:
      $ref: '#/definitions/ApiError'
  453-BusinessError:
    description: 'Business Exception'
    schema:
      $ref: '#/definitions/BusinessError'
  500-Exception:
    description: 'Internal Server Error'
    schema:
      $ref: '#/definitions/ApiError'

paths:
  /posts:

    post:
      tags:
        - Public
      summary: Create a new post
      description: Save a new post in the database by filling all the required fields
      operationId: createPost
      produces:
        - application/json
      consumes:
        - application/json

      parameters:
        - $ref: '#/parameters/post'
      responses:
        201:
          $ref: '#/responses/201-Created'
        400:
          $ref: '#/responses/400-BadRequest'
        401:
          $ref: '#/responses/401-Unauthorized'
        403:
          $ref: '#/responses/403-Forbidden'
        405:
          $ref: '#/responses/405-DataInvalid'
        500:
          $ref: '#/responses/500-Exception'


definitions:
  ApiError:
    type: object
    description: 'Error API responses'
    properties:
      code:
        type: integer
        format: int32
        description: 'Error ID'
      message:
        type: string
        description: 'Error Description'
      description:
        type: string
        description: 'Error Details'
      errors:
        type: array
        description: 'Membership Erros'
        items:
          $ref: '#/definitions/Error'

  BusinessError:
    type: object
    title: 'BusinessError'
    description: 'Error API response'
    properties:
      code:
        type: integer
        format: int32
        description: 'Error ID'
      message:
        type: string
        description: 'Error Details'
      description:
        type: string
        description: 'Error Details'
      errors:
        type: array
        description: 'Membership Errors'
        items:
          $ref: '#/definitions/Error'

  Error:
    type: object
    description: 'Error Entity'
    properties:
      code:
        type: string
        description: 'Error ID'
      message:
        type: string
        description: 'Error Description'
      nativeMessage:
        type: string
        description: 'Native Error description'

  CreatedPost:
    type: object
    title: Created post
    description: 'Response object for Post creation'
    properties:
      id:
        type: integer
        format: int64
        description: 'Post unique identifier'
        example: 1

  ClientList:
    type: array
    title: ClientList
    description: 'Object to describe a list composed by multiple instances of Client entity'
    items:
      $ref: '#/definitions/Post'

  User:
    type: object
    title: User
    description: 'Object to describe a single User entity'
    properties:
      id:
        type: integer
        description: 'User unique identifier'
        example: 1
      username:
        type: string
        description: 'User unique name'
        example: 'rpsilva10'
      joinedAt:
        type: string
        description: 'Date and time of creation'
        format: date-time
      postCount:
        type: number
        description: 'Total of posts for this user'
        format: int64
        example: 9592

  CreatePostRequest:
    type: object
    title: CreatePostObject
    description: 'Object to create a post'
    properties:
      content:
        type: string
        description: 'Post text content'
        maxLength: 777
        example: 'Lorem ipsulum'
      userId:
        type: integer
        format: int64
        description: 'Unique identifier from the user that is creating the post'
        example: 127
      type:
        type: string
        description: 'Post type'
        enum: ['ORIGINAL', 'REPOST', 'QUOTE']
    required:
      - content
      - userId
      - type


  Post:
    type: object
    title: Post
    description: 'Object to describe a single Post entity'
    properties:
      id:
        type: integer
        description: 'Post unique identifier'
        example: 1
      content:
        type: string
        description: 'Post text content'
        maxLength: 777
        example: 'Lorem ipsulum'
      user:
        allOf:
          - $ref: '#/definitions/User'
      createdAt:
        type: string
        description: 'Date and time of creation'
        format: date-time
      postType:
        allOf:
          - $ref: '#/definitions/User'


    required:
      - id
      - content
      - user
      - createdAt
